2017-06-14 15:52:45,654 ERROR [main] o.l.g.c.GeogigCLI [GeogigCLI.java:398] An unhandled error occurred: java.lang.ArrayIndexOutOfBoundsException: 3. See the log for more details.
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CacheHelper.get(ObjectDatabaseCacheInterceptor.java:226) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CacheHelper.get(ObjectDatabaseCacheInterceptor.java:211) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CachingObjectDatabase.get(ObjectDatabaseCacheInterceptor.java:103) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.ResolveObjectType._call(ResolveObjectType.java:41) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.ResolveObjectType._call(ResolveObjectType.java:20) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.ResolveTreeish.call(ResolveTreeish.java:91) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.ResolveTreeish._call(ResolveTreeish.java:73) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.ResolveTreeish._call(ResolveTreeish.java:27) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.DiffCount.getTree(DiffCount.java:136) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.DiffCount._call(DiffCount.java:110) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.DiffCount._call(DiffCount.java:34) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
	at org.locationtech.geogig.repository.impl.Index.countStaged(Index.java:350) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.porcelain.StatusOp._call(StatusOp.java:88) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.porcelain.StatusOp._call(StatusOp.java:31) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
	at org.locationtech.geogig.cli.porcelain.Status.runInternal(Status.java:74) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.AbstractCommand.run(AbstractCommand.java:68) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.GeogigCLI.executeInternal(GeogigCLI.java:528) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.GeogigCLI.execute(GeogigCLI.java:367) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.app.CLI.main(CLI.java:80) [geogig-cli-app-1.0.jar:1.0]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.locationtech.geogig.storage.datastream.SerializationFactoryProxy.read(SerializationFactoryProxy.java:68) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.storage.impl.AbstractObjectStore.get(AbstractObjectStore.java:170) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.storage.impl.AbstractObjectStore.get(AbstractObjectStore.java:112) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.get(ForwardingObjectDatabase.java:85) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$ValueLoader.call(ObjectDatabaseCacheInterceptor.java:182) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$ValueLoader.call(ObjectDatabaseCacheInterceptor.java:169) ~[geogig-core-1.0.jar:1.0]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739) ~[guava-18.0.jar:na]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CacheHelper.get(ObjectDatabaseCacheInterceptor.java:221) ~[geogig-core-1.0.jar:1.0]
	... 22 common frames omitted
2017-06-14 15:56:29,293 INFO [main] o.l.g.p.CreateDeduplicator [CreateDeduplicator.java:40] No DeduplicationService service found, using default heap based one
2017-06-14 15:56:30,376 ERROR [main] o.l.g.c.GeogigCLI [GeogigCLI.java:398] An unhandled error occurred: java.net.ConnectException: Connection refused: connect. See the log for more details.
java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-18.0.jar:na]
	at org.locationtech.geogig.remote.HttpRemoteRepo.listRefs(HttpRemoteRepo.java:180) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.plumbing.LsRemote._call(LsRemote.java:124) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.plumbing.LsRemote._call(LsRemote.java:33) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154) ~[geogig-api-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:199) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:48) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154) ~[geogig-api-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.PullOp._call(PullOp.java:196) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.PullOp._call(PullOp.java:33) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154) ~[geogig-api-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.porcelain.Pull.runInternal(Pull.java:101) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.AbstractCommand.run(AbstractCommand.java:68) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.GeogigCLI.executeInternal(GeogigCLI.java:530) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.GeogigCLI.execute(GeogigCLI.java:367) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.app.CLI.main(CLI.java:80) [geogig-cli-app-1.1.0.jar:1.1.0]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_121]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_121]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:1.8.0_121]
	at org.locationtech.geogig.remote.HttpUtils.connect(HttpUtils.java:491) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.remote.HttpRemoteRepo.listRefs(HttpRemoteRepo.java:162) ~[geogig-core-1.1.0.jar:1.1.0]
	... 14 common frames omitted
2017-06-14 15:56:43,718 INFO [main] o.l.g.p.CreateDeduplicator [CreateDeduplicator.java:40] No DeduplicationService service found, using default heap based one
2017-06-14 15:56:44,770 ERROR [main] o.l.g.c.GeogigCLI [GeogigCLI.java:398] An unhandled error occurred: java.net.ConnectException: Connection refused: connect. See the log for more details.
java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-18.0.jar:na]
	at org.locationtech.geogig.remote.HttpRemoteRepo.listRefs(HttpRemoteRepo.java:180) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.plumbing.LsRemote._call(LsRemote.java:124) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.plumbing.LsRemote._call(LsRemote.java:33) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154) ~[geogig-api-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:199) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.FetchOp._call(FetchOp.java:48) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154) ~[geogig-api-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.PullOp._call(PullOp.java:196) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.porcelain.PullOp._call(PullOp.java:33) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154) ~[geogig-api-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.porcelain.Pull.runInternal(Pull.java:101) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.AbstractCommand.run(AbstractCommand.java:68) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.GeogigCLI.executeInternal(GeogigCLI.java:530) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.GeogigCLI.execute(GeogigCLI.java:367) ~[geogig-cli-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.cli.app.CLI.main(CLI.java:80) [geogig-cli-app-1.1.0.jar:1.1.0]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_121]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_121]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_121]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:1.8.0_121]
	at org.locationtech.geogig.remote.HttpUtils.connect(HttpUtils.java:491) ~[geogig-core-1.1.0.jar:1.1.0]
	at org.locationtech.geogig.remote.HttpRemoteRepo.listRefs(HttpRemoteRepo.java:162) ~[geogig-core-1.1.0.jar:1.1.0]
	... 14 common frames omitted
