2017-06-14 15:47:28,811 ERROR [main] o.l.g.c.GeogigCLI [GeogigCLI.java:398] An unhandled error occurred: java.lang.ArrayIndexOutOfBoundsException: 3. See the log for more details.
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CacheHelper.get(ObjectDatabaseCacheInterceptor.java:226) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CachingObjectDatabase.get(ObjectDatabaseCacheInterceptor.java:109) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CachingObjectDatabase.getTree(ObjectDatabaseCacheInterceptor.java:114) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.DiffCount.getTree(DiffCount.java:139) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.DiffCount._call(DiffCount.java:110) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.plumbing.DiffCount._call(DiffCount.java:34) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
	at org.locationtech.geogig.repository.impl.Index.countStaged(Index.java:350) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.porcelain.StatusOp._call(StatusOp.java:88) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.porcelain.StatusOp._call(StatusOp.java:31) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:153) ~[geogig-api-1.0.jar:1.0]
	at org.locationtech.geogig.cli.porcelain.Status.runInternal(Status.java:74) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.AbstractCommand.run(AbstractCommand.java:68) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.GeogigCLI.executeInternal(GeogigCLI.java:528) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.GeogigCLI.execute(GeogigCLI.java:367) ~[geogig-cli-1.0.jar:1.0]
	at org.locationtech.geogig.cli.app.CLI.main(CLI.java:80) [geogig-cli-app-1.0.jar:1.0]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.locationtech.geogig.storage.datastream.SerializationFactoryProxy.read(SerializationFactoryProxy.java:68) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.storage.impl.AbstractObjectStore.get(AbstractObjectStore.java:170) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.storage.impl.AbstractObjectStore.get(AbstractObjectStore.java:112) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.get(ForwardingObjectDatabase.java:85) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$ValueLoader.call(ObjectDatabaseCacheInterceptor.java:182) ~[geogig-core-1.0.jar:1.0]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$ValueLoader.call(ObjectDatabaseCacheInterceptor.java:169) ~[geogig-core-1.0.jar:1.0]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739) ~[guava-18.0.jar:na]
	at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CacheHelper.get(ObjectDatabaseCacheInterceptor.java:221) ~[geogig-core-1.0.jar:1.0]
	... 15 common frames omitted
